# Bitcoin log growth curve

Aid: https://www.youtube.com/watch?v=gYm6OgeJAuE

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import curve_fit

In [3]:
df = pd.read_csv("../data/BTCUSDT-hour-target-features.csv")

In [5]:
df

,timestamp,open,high,low,close,volume,close_time,quote_av,trades,tb_base_av,...,volatility_dc_wband_10,volatility_pband_50,volatility_wband_20,volatility_ui_30,volume_cmf_50,volume_cmf_50_rate_200,volume_eom_amplified,volume_fi_amplified,volume_mfi_50,volume_nvi_o_close_rate_50
0,2017-08-17 04:00:00.000,4261.48,4313.62,4261.32,4308.83,47.181009,1502945999999,2.023661e+05,171,35.160503,...,NaN,0.636138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-17 05:00:00.000,4308.83,4328.69,4291.37,4315.32,23.234916,1502949599999,1.003048e+05,102,21.448071,...,NaN,0.635331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-17 06:00:00.000,4330.29,4345.45,4309.37,4324.35,7.229691,1502953199999,3.128231e+04,36,4.802861,...,NaN,0.660209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-17 07:00:00.000,4316.62,4349.99,4287.41,4349.99,4.443249,1502956799999,1.924106e+04,25,2.602292,...,NaN,0.866626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-17 08:00:00.000,4333.32,4377.85,4333.32,4360.69,0.972807,1502960399999,4.239504e+03,28,0.814655,...,NaN,0.895730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32885,2021-05-23 09:00:00,34376.00,35300.00,33925.18,34202.58,13905.215271,1621763999999,4.804456e+08,248349,6930.347913,...,12.205612,-0.914505,5.133607,7.435784,-0.035475,-0.000476,-23.363917,-16.773329,39.950499,0.413724
32886,2021-05-23 10:00:00,34207.02,35822.21,34118.72,35004.81,9389.783513,1621767599999,3.293869e+08,179166,4687.146563,...,12.181398,-0.525408,5.301701,7.223796,-0.040576,-0.000218,-23.196908,-16.644038,42.149835,0.424611
32887,2021-05-23 11:00:00,35004.82,35800.00,34600.00,35389.10,6744.387033,1621771199999,2.381694e+08,129096,3263.463404,...,11.700578,-0.319974,5.179989,6.976869,-0.042041,0.000036,-23.376503,-16.579486,42.146146,0.424611
32888,2021-05-23 12:00:00,35386.80,35800.00,33118.93,33944.77,17222.705813,1621774799999,5.928686e+08,297192,7952.349708,...,12.730327,-0.820926,5.682936,6.940117,-0.051912,-0.000034,-23.568716,-16.888813,39.502690,0.544276
32889,2021-05-23 13:00:00,33944.76,34169.76,32600.00,33642.07,17683.020616,1621778399999,5.895026e+08,333703,8450.044800,...,13.650420,-0.870474,5.926507,6.950493,-0.044347,0.000097,-23.637698,-16.924622,37.085862,0.570657